[package]
authors = ["chrispaig3"]
name = "lp"
version = "0.1.5"
description = "An embeddable plugin system for Rust applications."
edition = "2024"
license = "MIT"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
