[plugin]
authors = ["chrispaig3"]
name = "test_asset"
version = "0.1.0"
description = "A test asset for the plugin manager."
license = "MIT"
path = "/Users/chris/Dev/lp/test_fn/target/debug/libtest_fn.dylib"
